---
ID: "f949c81a-1647-43f8-8414-864ae3a0fe0c"
Parent: "315c2094-ebe1-45d3-b7f6-c57fec3d057c"
Template: "315c2094-ebe1-45d3-b7f6-c57fec3d057c"
Path: /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Card Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {3A7D27E5-B935-46DA-B8FB-FE1E260957D8}
    {315C2094-EBE1-45D3-B7F6-C57FEC3D057C}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071628Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2f3f8fb5-8ef9-407e-8831-096003217a19"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pbarron@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240311T154436Z
